workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - app_store_connect
    scripts:
      - name: Set up keychain
        script: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -archivePath build/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/Runner
    artifacts:
      - build/Runner.ipa
    environment:
      vars:
        KEYCHAIN_PASSWORD: Thunderup1
        APP_STORE_CONNECT_KEY_ID: U6BF49786N
        APP_STORE_CONNECT_ISSUER_ID: TJ3WB325FK
        APP_STORE_CONNECT_PRIVATE_KEY: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXQ6Tz4u1djsh++w0
                                        /Wx+nfh1eun+QP0iIfZ5TdvgGW+gCgYIKoZIzj0DAQehRANCAASD9rRk7dnQ0J/Z
                                        OJz1hZv8uh81I5nudSFt9TGUhd4WEIfMeyN6GeASkR2LiDd9O9/xNUEQnd7R1pUV
                                        5MsmQagX
    app_store_connect:
      key_id: $APP_STORE_CONNECT_KEY_ID
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      private_key: $APP_STORE_CONNECT_PRIVATE_KEY
    provisioning_profile:
      type: development
      bundle_identifier: com.test.distracteddriving
      bundle_identifier: com.test.distracteddriving.ImageNotification
